### ISSUE TITLE
1.9.1钱包手动设置手续费的问题

### ISSUE THREAD

**Issue by WilliamXuu** [withu2018/infinitecoin#2]
此版本钱包在手动设置手续费位置设置0，使用钱包自带的千2收取手续费没有任何问题
但是当手动设置一个手续费以后（为了提高矿工积极性，我设置的手续费肯定超过千2），在交易的时候，会经常出现设置的交易数量超限，您需要支付X IFC交易费。。。。这样的对话框。
然后这个X会出现很多倍数的增长，我目前遇到过最高67倍的手续费。。

**Comment by withu2018** [comment]
正在检查代码，可能是一个bug。非常感谢

**Comment by withu2018** [comment]
这个问题已经在1.9.1.4版本中修复。
