### ISSUE TITLE
1.9.1.0新版本，实现内循环，GOOD.

### ISSUE THREAD

**Issue by mirende7777** [withu2018/infinitecoin#4]
1.9.1.0新版本，实现内循环，GOOD。但是用来挖矿碎片太多，不能一次大额转出

**Comment by withu2018** [comment]
这是一个悖论，
1、如果允许一次性太多碎片在一个交易里的话，会影响区块链整体的性能。
2、每个交易都有size限制，对于挖矿来的碎片，接下去会开发一个小工具，在钱包运行的空闲时间自动化零为整，当然可能需要支付少许的转账手续费。
3、对于挖矿碎片的问题，需要矿池研究者去思考，如何降低每次挖矿中分摊的个数。
