### ISSUE TITLE
Petition

### ISSUE THREAD

**Issue by WilliamXuu** [withu2018/infinitecoin#5]
The wallet version 1.9.1.4 has internal links, so it seems quite inappropriate to promote its use abroad.I hope you can delete the links in your wallet and the links provided in the transaction block with the block chain browser, which can  be retained in the help page.
On behalf of the Basic Development Group, I would like to thank you very much for supporting the promotion of the Basic Development Group overseas along the way.

**Comment by withu2018** [comment]
Vsersion of 1.9.2.x,the links is defualut hidden.
I can build new Version at line 1.9.1.x, Revision 5
The new version will be released soon. It will be better. Please support it at that time.

**Comment by withu2018** [comment]
it's ok
